### ISSUE TITLE
behaviors settings should be able to pass in settings.

### ISSUE THREAD

**Issue by imjoshdean** [imjoshdean/beatz-bot#13]
Currently when passing in behaviors to a bot, you can only pass in the constructor function. This is okay sometimes; however, behaviors might have various settings that you want to pass in with it. I propose that you should be able to pass in either the constructor function or an object that contains both the constructor function as well as settings. Such as:

``` js
var beatzBot = new MascotBot({
  behaviors: [
    TestBehavior,
    {
        behavior: SampleBehavior,
        settings: {
          foo: 'bar',
          baz: 'qux'
        }
    }
  ]
```

**Comment by shirgoldbird** [comment]
Why wouldn't you do something like:

```
behaviors: [
    TestBehavior: {
       foo: 'bar',
       baz: 'qux'
    }
]
```

**Comment by imjoshdean** [comment]
Because we need to pass in the constructor function to be called to the bot, if we did this, we would only have the name of it, and the Mascot Bot code should not import any behaviors itself. That should all be done by whomever is creating an instance of one.
