### ISSUE TITLE
Create Karma Behavior

### ISSUE THREAD

**Issue by grantjbutler** [imjoshdean/beatz-bot#22]
Add the ability to keep track of a user's karma, via `@user++` and `@user--` messages, with an optional reason attached to the message. The implementation should probably mimic the [old behavior](https://github.com/BronyCon/spikebot/blob/master/modules/karma.js) in spikebot.

Random thought: Is it possible to get reactions on a message, as well as be notified when a reaction is added to a message? Might be another interesting way of giving a user karma, based off of a limit set of emoji that convey intent. 👍 👎 💯 👏 ❤️ 🎉 are all possibilities, mostly based off of the ones that GitHub uses as reactions to issues and comments.

**Comment by imjoshdean** [comment]
Regarding your random thought, yes. We have very specific emoji in mind already for that, don't you worry ❤️

**Comment by imjoshdean** [comment]
This has been implemented in an alpha and beta stage through https://github.com/imjoshdean/beatz-bot/pull/34 and other commits. Closing :heart:
