### ISSUE TITLE
Ignore Commands In Certain Scenarios

### ISSUE THREAD

**Issue by grantjbutler** [imjoshdean/beatz-bot#28]
In certain cases, commands should be ignored and not actually executed by beatz-bot. The main example would be in the case of a command being surrounded by back ticks (`rtd 6d2`), as that may generally be used when showing other users how commands work, or speculating on new syntax/commands.

It may also be desired that beatz-bot also ignores commands that are not at the start of a message ("... rtd should sum the values. Might look into that when I have a moment. (e.g. rtd 2d6 = You rolled 3, 2 (5))"), since it is likely that those commands are meant to be the subject of discussion, and not meant to be actually executed.

**Comment by dispatchrabbi** [comment]
@grantjbutler See #29 for another take on fixing this.

**Comment by imjoshdean** [comment]
I think there's merit to only wanting to care about the rtd message if it starts with it.
