### ISSUE TITLE
Responses to commands issued in threads should stay in the thread

### ISSUE THREAD

**Issue by shirgoldbird** [imjoshdean/beatz-bot#47]
Currently if a bot command like `user++` or `!badges` is given in a thread, the output will be put in the channel rather than the thread. The output should stay in the thread rather than confusing the channel. :)

**Comment by imjoshdean** [comment]
https://api.slack.com/docs/message-threading#using_the_rtm_api

Looks like this is pretty possible. Will investigate.

**Comment by imjoshdean** [comment]
Resolved with 807ec7937151d3431ab5ee4491a08b5e27dabc77
